using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.SqlClient;
using System.Web.Configuration;

/// <summary>
/// Summary description for AutoGeneratedID
/// </summary>
public class AutoGeneratedID
{
    private SqlConnection conn;
    private SqlCommand cmd;

	public AutoGeneratedID()
	{
		//
		// TODO: Add constructor logic here
		//
	}

    public SqlConnection sambung()
    {
        string strConn = WebConfigurationManager.ConnectionStrings["berita"].ConnectionString;
        conn = new SqlConnection(strConn);
        return conn;
    }


    public string AutoGenerateIDCat()
    {
        AutoGeneratedID koneksi = new AutoGeneratedID();
        conn = koneksi.sambung();
        string id = null;
        using (conn)
        {
            conn.Open();
            string sql = "SELECT TOP 1 ID_Kategori from Kategori ORDER BY ID_Kategori DESC";
            SqlCommand sqlcom = new SqlCommand(sql, conn);
            using (sqlcom)
            {
                SqlDataReader dr = sqlcom.ExecuteReader();
                if (dr.Read())
                {
                    id = dr.GetString(0);
                    string sub = id.Substring(3);
                    int a = Convert.ToInt32(sub) + 1;
                    if (a < 10)
                    {
                        id = "CAT00" + a;
                    }
                    else if (a < 100)
                    {
                        id = "CAT0" + a;
                    }
                    else if (a < 1000)
                    {
                        id = "CAT" + a;
                    }
                }
                else
                {
                    id = "CAT001";
                }
            }
            conn.Close();
        }
        return id;
    }
    public string AutoGenerateIDBer()
    {
        AutoGeneratedID koneksi = new AutoGeneratedID();
        conn = koneksi.sambung();
        string id = null;
        using (conn)
        {
            conn.Open();
            string sql = "SELECT TOP 1 ID_Berita from Berita ORDER BY ID_Berita DESC";
            SqlCommand sqlcom1 = new SqlCommand(sql, conn);
            using (sqlcom1)
            {
                SqlDataReader dr1 = sqlcom1.ExecuteReader();
                if (dr1.Read())
                {
                    id = dr1.GetString(0);
                    string sub = id.Substring(3);
                    int a = Convert.ToInt32(sub) + 1;
                    if (a < 10)
                    {
                        id = "BER00" + a;
                    }
                    else if (a < 100)
                    {
                        id = "BER0" + a;
                    }
                    else if (a < 1000)
                    {
                        id = "BER" + a;
                    }
                }
                else
                {
                    id = "BER001";
                }
            }
            conn.Close();
        }
        return id;
    }
    public string AutoGenerateIDAdmin()
    {
        AutoGeneratedID koneksi = new AutoGeneratedID();
        conn = koneksi.sambung();
        string id = null;
        using (conn)
        {
            conn.Open();
            string sql = "SELECT TOP 1 ID_Admin from Admin ORDER BY ID_Admin DESC";
            SqlCommand sqlcom1 = new SqlCommand(sql, conn);
            using (sqlcom1)
            {
                SqlDataReader dr1 = sqlcom1.ExecuteReader();
                if (dr1.Read())
                {
                    id = dr1.GetString(0);
                    string sub = id.Substring(3);
                    int a = Convert.ToInt32(sub) + 1;
                    if (a < 10)
                    {
                        id = "ADM00" + a;
                    }
                    else if (a < 100)
                    {
                        id = "ADM0" + a;
                    }
                    else if (a < 1000)
                    {
                        id = "ADM" + a;
                    }
                }
                else
                {
                    id = "ADM001";
                }
            }
            conn.Close();
        }
        return id;
    }
}