using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Data;
using System.Web.Configuration;
using System.Text;

public partial class AdminWeb_AddAdmin : System.Web.UI.Page
{
    private SqlConnection koneksi;
    protected void Page_Load(object sender, EventArgs e)
    {
        string strConn = WebConfigurationManager.ConnectionStrings["berita"].ConnectionString;
        koneksi = new SqlConnection(strConn);
        adminid();
        displaydataadmin();
        if (Session["Id"] == "1" && Session["Username"] != "")
        {
            User.Text += Session["Username"];
        }
        else
        {
            Session.RemoveAll();
            Response.Redirect("Login.aspx");
        }

        //if (!IsPostBack)
        //{
        //    Response.Cache.SetCacheability(HttpCacheability.NoCache);
        //    Response.Cache.SetExpires(DateTime.Now.AddSeconds(-1));
        //    Response.Cache.SetNoStore();
        //}

        Response.Cache.SetNoStore();
        Response.Cache.SetCacheability(HttpCacheability.NoCache);
    }
    private void adminid()
    {
        AutoGeneratedID auto = new AutoGeneratedID();
        string id = auto.AutoGenerateIDAdmin();
        txtid.Text = id;
    }
    protected void txtid_TextChanged(object sender, EventArgs e)
    {
        adminid();
    }
    protected void simpanKat_Click(object sender, EventArgs e)
    {
        try
        {
            crud smpn = new crud();
            smpn.simpanadmin(txtid.Text, txtnama.Text, txtuser.Text, txtpswd1.Text);
            Response.Write("<script>alert('Data Success Added');</script>");
            Response.Redirect("AddAdmin.aspx");

        }
        catch (Exception ex)
        {

            txtError.Text = ex.Message;
        }

    }
    public void displaydataadmin()
    {

        //Building an HTML string.
        StringBuilder html = new StringBuilder();

        //Table start.
        html.Append("<table class='table table-bordered'>");

        html.Append("<tr>");
        html.Append("<th>ID Admin</th>");
        html.Append("<th>Name</th>");
        html.Append("<th>Username</th>");
        html.Append("</tr>");


        //Building the Data rows.

        koneksi.Open();
        string sql = "select * from Admin order by ID_Admin desc";
        SqlCommand sqlcon = new SqlCommand(sql, koneksi);
        using (koneksi)
        {
            SqlDataReader dr = sqlcon.ExecuteReader();
            while (dr.Read())
            {
                html.Append("<tr>");
                html.Append("<td>" + dr.GetString(0) + "</td>");
                html.Append("<td>" + dr.GetString(1) + "</td>");
                html.Append("<td>" + dr.GetString(2) + "</td>");
                html.Append("</tr>");
            }
        }


        //Table end.
        html.Append("</table>");

        //Append the HTML string to Placeholder.
        Datacat.Controls.Add(new Literal { Text = html.ToString() });
        koneksi.Close();
    }
}